### ISSUE TITLE
Diagramme de séquence illisible

### ISSUE THREAD

**Issue by nathieb** [france-connect/Documentation-AgentConnect#1]
Bonjour khadija,

le document, impression d'écran des appels https://github.com/france-connect/Documentation-AgentConnect/blob/main/doc%20FI.md#d%C3%A9tail-du-fonctionnement est illisible. Il serait bien d'augmenter la définition.

Olivier T. ANSC

**Comment by maxbes** [comment]
J'en profite pour signaler à qui lirai ceci que la flèche GET[userinfo_endpoint] devrait faire AC->FI et non pas FC->FI.

FC n'existant pas dans cette cinématique

**Comment by Tcing** [comment]
Hello !

Le diagramme est illisible. Je vous propose d'utiliser [mermaid markdown](https://mermaid-js.github.io/mermaid/#/) qui propose un grand choix de types de visualisations et facilite le suivie des modification.

**Comment by rdubigny** [comment]
Merci pour ces suggestions. Nous allons reprendre cette documentation en ce sens.
